apiVersion: v1
kind: ReplicationController
metadata:
   name: testrc
spec:
  replicas: 2
  selector:
    myname: shabnam
  template:
    metadata:
      name: testrcpod
      labels:
        myname: shabnam
    spec:
      containers:
       - name: coo
         image: ubuntu
         command: ["/bin/bash" , "-c", "while true; do echo shabnam; sleep 5 ; done"]
