apiVersion: apps/v1
kind: Deployment
metadata:
   name: deploytestpod
spec:
   replicas: 1
   selector:
     matchLabels:
       name: deployment
   template:
     metadata:
       name: podtest
       labels:
         name: deployment
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
           - containerPort: 80
