apiVersion: v1
kind: Pod
metadata:
  name: testpod1
spec:
  containers:
    - name: c00
      image: nginx
      ports:
        - containerPort: 80


apiVersion: v1
kind: Pod
metadata:
  name: testpod2
spec:
  containers:
    - name: c01
      image: httpd
      ports:
        - containerPort: 80
