apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myebsvolclaim
spec:
  volumeName: mypd
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

      
      
------------------------------------------------------------
kind: Deployment
apiVersion: apps/v1
metadata:
        name: pvdeploy
        labels:
                apps: nginx
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: mypv
        template:
                metadata:
                        labels:
                                app: mypv
                spec:
                        containers:
                                - name: shell
                                  image: centos
                                  command: ["/bin/bash","-c"," sleep 50"]
                                  volumeMounts:
                                    - mountPath: "/tmp/persistent"
                                      name: mypd
                        volumes:
                          - name: mypd
                            persistentVolumeClaim:
                              claimName: myebsvolclaim

----------------------------------------------------

apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebsvol
spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0846638ac23b6cf6b
    fsType: ext4

