kind: Pod
apiVersion: v1
metadata:
        name: v1
spec:
        containers:
                - name: ubuntu
                  image: ubuntu
                  command: ["/bin/bash","-c","while true ;do echo vishal; sleep 4;done"]
                  volumeMounts:
                          - name: xchange
                            mountPath: "tmp/xchange"
        volumes:
               - name: xchange
                 emptyDir: {}

